//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Impendulo.ReportDemoStudentReport.DataSource {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("StudentReports")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class StudentReports : global::System.Data.DataSet {
        
        private Reports_StudentReportsDataTable tableReports_StudentReports;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public StudentReports() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected StudentReports(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["Reports_StudentReports"] != null)) {
                    base.Tables.Add(new Reports_StudentReportsDataTable(ds.Tables["Reports_StudentReports"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Reports_StudentReportsDataTable Reports_StudentReports {
            get {
                return this.tableReports_StudentReports;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            StudentReports cln = ((StudentReports)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Reports_StudentReports"] != null)) {
                    base.Tables.Add(new Reports_StudentReportsDataTable(ds.Tables["Reports_StudentReports"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableReports_StudentReports = ((Reports_StudentReportsDataTable)(base.Tables["Reports_StudentReports"]));
            if ((initTable == true)) {
                if ((this.tableReports_StudentReports != null)) {
                    this.tableReports_StudentReports.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "StudentReports";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/StudentReports.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableReports_StudentReports = new Reports_StudentReportsDataTable();
            base.Tables.Add(this.tableReports_StudentReports);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeReports_StudentReports() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            StudentReports ds = new StudentReports();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void Reports_StudentReportsRowChangeEventHandler(object sender, Reports_StudentReportsRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class Reports_StudentReportsDataTable : global::System.Data.TypedTableBase<Reports_StudentReportsRow> {
            
            private global::System.Data.DataColumn columnIndividualID;
            
            private global::System.Data.DataColumn columnIndividualFirstName;
            
            private global::System.Data.DataColumn columnIndividualSecondName;
            
            private global::System.Data.DataColumn columnIndividualLastname;
            
            private global::System.Data.DataColumn columnTitle;
            
            private global::System.Data.DataColumn columnStudentCurrentPosition;
            
            private global::System.Data.DataColumn columnStudentIDNumber;
            
            private global::System.Data.DataColumn columnDisability;
            
            private global::System.Data.DataColumn columnEthnicity;
            
            private global::System.Data.DataColumn columnMaritialStatus;
            
            private global::System.Data.DataColumn columnQualificationLevel;
            
            private global::System.Data.DataColumn columnGender;
            
            private global::System.Data.DataColumn columnAddressLineOne;
            
            private global::System.Data.DataColumn columnAddressLineTwo;
            
            private global::System.Data.DataColumn columnAddressTown;
            
            private global::System.Data.DataColumn columnAddressSuburb;
            
            private global::System.Data.DataColumn columnAddressAreaCode;
            
            private global::System.Data.DataColumn columnAddressIsDefault;
            
            private global::System.Data.DataColumn columnAddressModifiedDate;
            
            private global::System.Data.DataColumn columnCountryName;
            
            private global::System.Data.DataColumn columnProvince;
            
            private global::System.Data.DataColumn columnAddressType;
            
            private global::System.Data.DataColumn columnContactDetailValue;
            
            private global::System.Data.DataColumn columnContactType;
            
            private static System.DateTime columnAddressModifiedDate_defaultValue = global::System.DateTime.Parse("2001-01-01T00:00:00");
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Reports_StudentReportsDataTable() {
                this.TableName = "Reports_StudentReports";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal Reports_StudentReportsDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected Reports_StudentReportsDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IndividualIDColumn {
                get {
                    return this.columnIndividualID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IndividualFirstNameColumn {
                get {
                    return this.columnIndividualFirstName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IndividualSecondNameColumn {
                get {
                    return this.columnIndividualSecondName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IndividualLastnameColumn {
                get {
                    return this.columnIndividualLastname;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TitleColumn {
                get {
                    return this.columnTitle;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn StudentCurrentPositionColumn {
                get {
                    return this.columnStudentCurrentPosition;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn StudentIDNumberColumn {
                get {
                    return this.columnStudentIDNumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DisabilityColumn {
                get {
                    return this.columnDisability;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn EthnicityColumn {
                get {
                    return this.columnEthnicity;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MaritialStatusColumn {
                get {
                    return this.columnMaritialStatus;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QualificationLevelColumn {
                get {
                    return this.columnQualificationLevel;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn GenderColumn {
                get {
                    return this.columnGender;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AddressLineOneColumn {
                get {
                    return this.columnAddressLineOne;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AddressLineTwoColumn {
                get {
                    return this.columnAddressLineTwo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AddressTownColumn {
                get {
                    return this.columnAddressTown;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AddressSuburbColumn {
                get {
                    return this.columnAddressSuburb;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AddressAreaCodeColumn {
                get {
                    return this.columnAddressAreaCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AddressIsDefaultColumn {
                get {
                    return this.columnAddressIsDefault;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AddressModifiedDateColumn {
                get {
                    return this.columnAddressModifiedDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CountryNameColumn {
                get {
                    return this.columnCountryName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ProvinceColumn {
                get {
                    return this.columnProvince;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AddressTypeColumn {
                get {
                    return this.columnAddressType;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ContactDetailValueColumn {
                get {
                    return this.columnContactDetailValue;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ContactTypeColumn {
                get {
                    return this.columnContactType;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Reports_StudentReportsRow this[int index] {
                get {
                    return ((Reports_StudentReportsRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event Reports_StudentReportsRowChangeEventHandler Reports_StudentReportsRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event Reports_StudentReportsRowChangeEventHandler Reports_StudentReportsRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event Reports_StudentReportsRowChangeEventHandler Reports_StudentReportsRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event Reports_StudentReportsRowChangeEventHandler Reports_StudentReportsRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddReports_StudentReportsRow(Reports_StudentReportsRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Reports_StudentReportsRow AddReports_StudentReportsRow(
                        int IndividualID, 
                        string IndividualFirstName, 
                        string IndividualSecondName, 
                        string IndividualLastname, 
                        string Title, 
                        string StudentCurrentPosition, 
                        string StudentIDNumber, 
                        string Disability, 
                        string Ethnicity, 
                        string MaritialStatus, 
                        string QualificationLevel, 
                        string Gender, 
                        string AddressLineOne, 
                        string AddressLineTwo, 
                        string AddressTown, 
                        string AddressSuburb, 
                        string AddressAreaCode, 
                        bool AddressIsDefault, 
                        System.DateTime AddressModifiedDate, 
                        string CountryName, 
                        string Province, 
                        string AddressType, 
                        string ContactDetailValue, 
                        string ContactType) {
                Reports_StudentReportsRow rowReports_StudentReportsRow = ((Reports_StudentReportsRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        IndividualID,
                        IndividualFirstName,
                        IndividualSecondName,
                        IndividualLastname,
                        Title,
                        StudentCurrentPosition,
                        StudentIDNumber,
                        Disability,
                        Ethnicity,
                        MaritialStatus,
                        QualificationLevel,
                        Gender,
                        AddressLineOne,
                        AddressLineTwo,
                        AddressTown,
                        AddressSuburb,
                        AddressAreaCode,
                        AddressIsDefault,
                        AddressModifiedDate,
                        CountryName,
                        Province,
                        AddressType,
                        ContactDetailValue,
                        ContactType};
                rowReports_StudentReportsRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowReports_StudentReportsRow);
                return rowReports_StudentReportsRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                Reports_StudentReportsDataTable cln = ((Reports_StudentReportsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new Reports_StudentReportsDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnIndividualID = base.Columns["IndividualID"];
                this.columnIndividualFirstName = base.Columns["IndividualFirstName"];
                this.columnIndividualSecondName = base.Columns["IndividualSecondName"];
                this.columnIndividualLastname = base.Columns["IndividualLastname"];
                this.columnTitle = base.Columns["Title"];
                this.columnStudentCurrentPosition = base.Columns["StudentCurrentPosition"];
                this.columnStudentIDNumber = base.Columns["StudentIDNumber"];
                this.columnDisability = base.Columns["Disability"];
                this.columnEthnicity = base.Columns["Ethnicity"];
                this.columnMaritialStatus = base.Columns["MaritialStatus"];
                this.columnQualificationLevel = base.Columns["QualificationLevel"];
                this.columnGender = base.Columns["Gender"];
                this.columnAddressLineOne = base.Columns["AddressLineOne"];
                this.columnAddressLineTwo = base.Columns["AddressLineTwo"];
                this.columnAddressTown = base.Columns["AddressTown"];
                this.columnAddressSuburb = base.Columns["AddressSuburb"];
                this.columnAddressAreaCode = base.Columns["AddressAreaCode"];
                this.columnAddressIsDefault = base.Columns["AddressIsDefault"];
                this.columnAddressModifiedDate = base.Columns["AddressModifiedDate"];
                this.columnCountryName = base.Columns["CountryName"];
                this.columnProvince = base.Columns["Province"];
                this.columnAddressType = base.Columns["AddressType"];
                this.columnContactDetailValue = base.Columns["ContactDetailValue"];
                this.columnContactType = base.Columns["ContactType"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnIndividualID = new global::System.Data.DataColumn("IndividualID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndividualID);
                this.columnIndividualFirstName = new global::System.Data.DataColumn("IndividualFirstName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndividualFirstName);
                this.columnIndividualSecondName = new global::System.Data.DataColumn("IndividualSecondName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndividualSecondName);
                this.columnIndividualLastname = new global::System.Data.DataColumn("IndividualLastname", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndividualLastname);
                this.columnTitle = new global::System.Data.DataColumn("Title", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTitle);
                this.columnStudentCurrentPosition = new global::System.Data.DataColumn("StudentCurrentPosition", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStudentCurrentPosition);
                this.columnStudentIDNumber = new global::System.Data.DataColumn("StudentIDNumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStudentIDNumber);
                this.columnDisability = new global::System.Data.DataColumn("Disability", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDisability);
                this.columnEthnicity = new global::System.Data.DataColumn("Ethnicity", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEthnicity);
                this.columnMaritialStatus = new global::System.Data.DataColumn("MaritialStatus", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMaritialStatus);
                this.columnQualificationLevel = new global::System.Data.DataColumn("QualificationLevel", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQualificationLevel);
                this.columnGender = new global::System.Data.DataColumn("Gender", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGender);
                this.columnAddressLineOne = new global::System.Data.DataColumn("AddressLineOne", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAddressLineOne);
                this.columnAddressLineTwo = new global::System.Data.DataColumn("AddressLineTwo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAddressLineTwo);
                this.columnAddressTown = new global::System.Data.DataColumn("AddressTown", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAddressTown);
                this.columnAddressSuburb = new global::System.Data.DataColumn("AddressSuburb", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAddressSuburb);
                this.columnAddressAreaCode = new global::System.Data.DataColumn("AddressAreaCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAddressAreaCode);
                this.columnAddressIsDefault = new global::System.Data.DataColumn("AddressIsDefault", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAddressIsDefault);
                this.columnAddressModifiedDate = new global::System.Data.DataColumn("AddressModifiedDate", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAddressModifiedDate);
                this.columnCountryName = new global::System.Data.DataColumn("CountryName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCountryName);
                this.columnProvince = new global::System.Data.DataColumn("Province", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnProvince);
                this.columnAddressType = new global::System.Data.DataColumn("AddressType", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAddressType);
                this.columnContactDetailValue = new global::System.Data.DataColumn("ContactDetailValue", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnContactDetailValue);
                this.columnContactType = new global::System.Data.DataColumn("ContactType", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnContactType);
                this.columnIndividualID.DefaultValue = ((int)(0));
                this.columnIndividualFirstName.AllowDBNull = false;
                this.columnIndividualFirstName.MaxLength = 30;
                this.columnIndividualSecondName.AllowDBNull = false;
                this.columnIndividualSecondName.MaxLength = 30;
                this.columnIndividualLastname.AllowDBNull = false;
                this.columnIndividualLastname.MaxLength = 30;
                this.columnTitle.AllowDBNull = false;
                this.columnTitle.MaxLength = 25;
                this.columnStudentCurrentPosition.AllowDBNull = false;
                this.columnStudentCurrentPosition.MaxLength = 50;
                this.columnStudentIDNumber.AllowDBNull = false;
                this.columnStudentIDNumber.MaxLength = 15;
                this.columnDisability.MaxLength = 25;
                this.columnEthnicity.MaxLength = 25;
                this.columnMaritialStatus.AllowDBNull = false;
                this.columnMaritialStatus.MaxLength = 25;
                this.columnQualificationLevel.AllowDBNull = false;
                this.columnQualificationLevel.MaxLength = 100;
                this.columnGender.AllowDBNull = false;
                this.columnGender.MaxLength = 20;
                this.columnAddressLineOne.MaxLength = 100;
                this.columnAddressLineTwo.MaxLength = 100;
                this.columnAddressTown.MaxLength = 50;
                this.columnAddressSuburb.MaxLength = 50;
                this.columnAddressAreaCode.MaxLength = 10;
                this.columnAddressIsDefault.DefaultValue = ((bool)(true));
                this.columnAddressModifiedDate.DefaultValue = ((System.DateTime)(Reports_StudentReportsDataTable.columnAddressModifiedDate_defaultValue));
                this.columnCountryName.MaxLength = 50;
                this.columnProvince.MaxLength = 50;
                this.columnAddressType.MaxLength = 25;
                this.columnContactDetailValue.MaxLength = 100;
                this.columnContactType.MaxLength = 50;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Reports_StudentReportsRow NewReports_StudentReportsRow() {
                return ((Reports_StudentReportsRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new Reports_StudentReportsRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(Reports_StudentReportsRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Reports_StudentReportsRowChanged != null)) {
                    this.Reports_StudentReportsRowChanged(this, new Reports_StudentReportsRowChangeEvent(((Reports_StudentReportsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Reports_StudentReportsRowChanging != null)) {
                    this.Reports_StudentReportsRowChanging(this, new Reports_StudentReportsRowChangeEvent(((Reports_StudentReportsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Reports_StudentReportsRowDeleted != null)) {
                    this.Reports_StudentReportsRowDeleted(this, new Reports_StudentReportsRowChangeEvent(((Reports_StudentReportsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Reports_StudentReportsRowDeleting != null)) {
                    this.Reports_StudentReportsRowDeleting(this, new Reports_StudentReportsRowChangeEvent(((Reports_StudentReportsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveReports_StudentReportsRow(Reports_StudentReportsRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                StudentReports ds = new StudentReports();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "Reports_StudentReportsDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class Reports_StudentReportsRow : global::System.Data.DataRow {
            
            private Reports_StudentReportsDataTable tableReports_StudentReports;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal Reports_StudentReportsRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableReports_StudentReports = ((Reports_StudentReportsDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int IndividualID {
                get {
                    try {
                        return ((int)(this[this.tableReports_StudentReports.IndividualIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IndividualID\' in table \'Reports_StudentReports\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableReports_StudentReports.IndividualIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string IndividualFirstName {
                get {
                    return ((string)(this[this.tableReports_StudentReports.IndividualFirstNameColumn]));
                }
                set {
                    this[this.tableReports_StudentReports.IndividualFirstNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string IndividualSecondName {
                get {
                    return ((string)(this[this.tableReports_StudentReports.IndividualSecondNameColumn]));
                }
                set {
                    this[this.tableReports_StudentReports.IndividualSecondNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string IndividualLastname {
                get {
                    return ((string)(this[this.tableReports_StudentReports.IndividualLastnameColumn]));
                }
                set {
                    this[this.tableReports_StudentReports.IndividualLastnameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Title {
                get {
                    return ((string)(this[this.tableReports_StudentReports.TitleColumn]));
                }
                set {
                    this[this.tableReports_StudentReports.TitleColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string StudentCurrentPosition {
                get {
                    return ((string)(this[this.tableReports_StudentReports.StudentCurrentPositionColumn]));
                }
                set {
                    this[this.tableReports_StudentReports.StudentCurrentPositionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string StudentIDNumber {
                get {
                    return ((string)(this[this.tableReports_StudentReports.StudentIDNumberColumn]));
                }
                set {
                    this[this.tableReports_StudentReports.StudentIDNumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Disability {
                get {
                    if (this.IsDisabilityNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableReports_StudentReports.DisabilityColumn]));
                    }
                }
                set {
                    this[this.tableReports_StudentReports.DisabilityColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Ethnicity {
                get {
                    if (this.IsEthnicityNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableReports_StudentReports.EthnicityColumn]));
                    }
                }
                set {
                    this[this.tableReports_StudentReports.EthnicityColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string MaritialStatus {
                get {
                    return ((string)(this[this.tableReports_StudentReports.MaritialStatusColumn]));
                }
                set {
                    this[this.tableReports_StudentReports.MaritialStatusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string QualificationLevel {
                get {
                    return ((string)(this[this.tableReports_StudentReports.QualificationLevelColumn]));
                }
                set {
                    this[this.tableReports_StudentReports.QualificationLevelColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Gender {
                get {
                    return ((string)(this[this.tableReports_StudentReports.GenderColumn]));
                }
                set {
                    this[this.tableReports_StudentReports.GenderColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string AddressLineOne {
                get {
                    if (this.IsAddressLineOneNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableReports_StudentReports.AddressLineOneColumn]));
                    }
                }
                set {
                    this[this.tableReports_StudentReports.AddressLineOneColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string AddressLineTwo {
                get {
                    if (this.IsAddressLineTwoNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableReports_StudentReports.AddressLineTwoColumn]));
                    }
                }
                set {
                    this[this.tableReports_StudentReports.AddressLineTwoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string AddressTown {
                get {
                    if (this.IsAddressTownNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableReports_StudentReports.AddressTownColumn]));
                    }
                }
                set {
                    this[this.tableReports_StudentReports.AddressTownColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string AddressSuburb {
                get {
                    if (this.IsAddressSuburbNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableReports_StudentReports.AddressSuburbColumn]));
                    }
                }
                set {
                    this[this.tableReports_StudentReports.AddressSuburbColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string AddressAreaCode {
                get {
                    if (this.IsAddressAreaCodeNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableReports_StudentReports.AddressAreaCodeColumn]));
                    }
                }
                set {
                    this[this.tableReports_StudentReports.AddressAreaCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool AddressIsDefault {
                get {
                    try {
                        return ((bool)(this[this.tableReports_StudentReports.AddressIsDefaultColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AddressIsDefault\' in table \'Reports_StudentReports\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableReports_StudentReports.AddressIsDefaultColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime AddressModifiedDate {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableReports_StudentReports.AddressModifiedDateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AddressModifiedDate\' in table \'Reports_StudentReports\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableReports_StudentReports.AddressModifiedDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string CountryName {
                get {
                    if (this.IsCountryNameNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableReports_StudentReports.CountryNameColumn]));
                    }
                }
                set {
                    this[this.tableReports_StudentReports.CountryNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Province {
                get {
                    if (this.IsProvinceNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableReports_StudentReports.ProvinceColumn]));
                    }
                }
                set {
                    this[this.tableReports_StudentReports.ProvinceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string AddressType {
                get {
                    if (this.IsAddressTypeNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableReports_StudentReports.AddressTypeColumn]));
                    }
                }
                set {
                    this[this.tableReports_StudentReports.AddressTypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ContactDetailValue {
                get {
                    if (this.IsContactDetailValueNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableReports_StudentReports.ContactDetailValueColumn]));
                    }
                }
                set {
                    this[this.tableReports_StudentReports.ContactDetailValueColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ContactType {
                get {
                    if (this.IsContactTypeNull()) {
                        return null;
                    }
                    else {
                        return ((string)(this[this.tableReports_StudentReports.ContactTypeColumn]));
                    }
                }
                set {
                    this[this.tableReports_StudentReports.ContactTypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsIndividualIDNull() {
                return this.IsNull(this.tableReports_StudentReports.IndividualIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetIndividualIDNull() {
                this[this.tableReports_StudentReports.IndividualIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDisabilityNull() {
                return this.IsNull(this.tableReports_StudentReports.DisabilityColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDisabilityNull() {
                this[this.tableReports_StudentReports.DisabilityColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsEthnicityNull() {
                return this.IsNull(this.tableReports_StudentReports.EthnicityColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetEthnicityNull() {
                this[this.tableReports_StudentReports.EthnicityColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAddressLineOneNull() {
                return this.IsNull(this.tableReports_StudentReports.AddressLineOneColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAddressLineOneNull() {
                this[this.tableReports_StudentReports.AddressLineOneColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAddressLineTwoNull() {
                return this.IsNull(this.tableReports_StudentReports.AddressLineTwoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAddressLineTwoNull() {
                this[this.tableReports_StudentReports.AddressLineTwoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAddressTownNull() {
                return this.IsNull(this.tableReports_StudentReports.AddressTownColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAddressTownNull() {
                this[this.tableReports_StudentReports.AddressTownColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAddressSuburbNull() {
                return this.IsNull(this.tableReports_StudentReports.AddressSuburbColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAddressSuburbNull() {
                this[this.tableReports_StudentReports.AddressSuburbColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAddressAreaCodeNull() {
                return this.IsNull(this.tableReports_StudentReports.AddressAreaCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAddressAreaCodeNull() {
                this[this.tableReports_StudentReports.AddressAreaCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAddressIsDefaultNull() {
                return this.IsNull(this.tableReports_StudentReports.AddressIsDefaultColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAddressIsDefaultNull() {
                this[this.tableReports_StudentReports.AddressIsDefaultColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAddressModifiedDateNull() {
                return this.IsNull(this.tableReports_StudentReports.AddressModifiedDateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAddressModifiedDateNull() {
                this[this.tableReports_StudentReports.AddressModifiedDateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCountryNameNull() {
                return this.IsNull(this.tableReports_StudentReports.CountryNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCountryNameNull() {
                this[this.tableReports_StudentReports.CountryNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsProvinceNull() {
                return this.IsNull(this.tableReports_StudentReports.ProvinceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetProvinceNull() {
                this[this.tableReports_StudentReports.ProvinceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAddressTypeNull() {
                return this.IsNull(this.tableReports_StudentReports.AddressTypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAddressTypeNull() {
                this[this.tableReports_StudentReports.AddressTypeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsContactDetailValueNull() {
                return this.IsNull(this.tableReports_StudentReports.ContactDetailValueColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetContactDetailValueNull() {
                this[this.tableReports_StudentReports.ContactDetailValueColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsContactTypeNull() {
                return this.IsNull(this.tableReports_StudentReports.ContactTypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetContactTypeNull() {
                this[this.tableReports_StudentReports.ContactTypeColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class Reports_StudentReportsRowChangeEvent : global::System.EventArgs {
            
            private Reports_StudentReportsRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Reports_StudentReportsRowChangeEvent(Reports_StudentReportsRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Reports_StudentReportsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591