//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentReport
    {
        public int AssessmentReportID { get; set; }
        public int AssessmentID { get; set; }
        public int ImageID { get; set; }
        public System.DateTime DateReportUploaded { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual File File { get; set; }
    }
}
