//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assessment()
        {
            this.AssessmentModules = new ObservableListSource<AssessmentModule>();
            this.AssessmentReports = new ObservableListSource<AssessmentReport>();
        }
    
        public int AssessmentID { get; set; }
        public int CurriculumCourseEnrollmentID { get; set; }
        public System.DateTime AssessmentDateCompleted { get; set; }
        public System.DateTime AssessmentDateStarted { get; set; }
        public System.DateTime AssessmentDateSubmitted { get; set; }
        public int AssessmentRecommendationID { get; set; }
    
        public virtual AssessmentFeedBackForm AssessmentFeedBackForm { get; set; }
        public virtual CurriculumCourseEnrollment CurriculumCourseEnrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<AssessmentModule> AssessmentModules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<AssessmentReport> AssessmentReports { get; set; }
        public virtual LookupAssessmentRecommendation LookupAssessmentRecommendation { get; set; }
    }
}
