//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentModule()
        {
            this.AssessmentModuleActivities = new ObservableListSource<AssessmentModuleActivity>();
        }
    
        public int AssessmentModuleID { get; set; }
        public int AssessmentID { get; set; }
        public int CurriculumCourseModuleID { get; set; }
        public int PracticalAssessmentStatusID { get; set; }
        public int TheoriticalAssessmentStatusID { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<AssessmentModuleActivity> AssessmentModuleActivities { get; set; }
        public virtual Assessment Assessment { get; set; }
        public virtual CurriculumCourseModule CurriculumCourseModule { get; set; }
        public virtual LookupPracticalAssessmentStatus LookupPracticalAssessmentStatus { get; set; }
        public virtual LookupTheoriticalAssesmentStatus LookupTheoriticalAssesmentStatus { get; set; }
    }
}
