//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentModuleActivity
    {
        public int AssessmentModuleActivityID { get; set; }
        public int AssessmentModuleID { get; set; }
        public int ActivityID { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual AssessmentModule AssessmentModule { get; set; }
    }
}
