//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyStudentProgressFile
    {
        public int CompanyStudentProgressFileID { get; set; }
        public int CompanyProgressFileID { get; set; }
        public int StudentProgressFileID { get; set; }
    
        public virtual CompanyProgressFile CompanyProgressFile { get; set; }
        public virtual StudentProgressFile StudentProgressFile { get; set; }
    }
}
