//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProgressFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyProgressFile()
        {
            this.CompanyStudentProgressFiles = new ObservableListSource<CompanyStudentProgressFile>();
        }
    
        public int CompanyProgressFileID { get; set; }
        public int CompanyID { get; set; }
        public System.DateTime DateLastUpdated { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ProgressFile ProgressFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<CompanyStudentProgressFile> CompanyStudentProgressFiles { get; set; }
    }
}
