//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.CurriculumCourses = new ObservableListSource<CurriculumCourse>();
            this.FacilitatorAssociatedCourses = new ObservableListSource<FacilitatorAssociatedCourse>();
            this.VenueAssociatedCourses = new ObservableListSource<VenueAssociatedCourse>();
        }
    
        public int CourseID { get; set; }
        public int DepartmentID { get; set; }
        public string CourseName { get; set; }
        public string CourseDescription { get; set; }
    
        public virtual LookupDepartment LookupDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<CurriculumCourse> CurriculumCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<FacilitatorAssociatedCourse> FacilitatorAssociatedCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<VenueAssociatedCourse> VenueAssociatedCourses { get; set; }
    }
}
