//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSystemOutGoingMessageAttachment
    {
        public int EmailSystemOutGoingMessageAttachmentID { get; set; }
        public int EmailSystemOutGoingMessageID { get; set; }
        public byte[] AttachementImage { get; set; }
    
        public virtual EmailSystemOutGoingMessage EmailSystemOutGoingMessage { get; set; }
    }
}
