//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSystemOutGoingMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailSystemOutGoingMessage()
        {
            this.EmailSystemOutGoingMessageAttachments = new ObservableListSource<EmailSystemOutGoingMessageAttachment>();
        }
    
        public int EmailSystemOutGoingMessageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<EmailSystemOutGoingMessageAttachment> EmailSystemOutGoingMessageAttachments { get; set; }
    }
}
