//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enquiry()
        {
            this.EquiryHistories = new ObservableListSource<EquiryHistory>();
            this.Companies = new ObservableListSource<Company>();
            this.EmailMessageRepositories = new ObservableListSource<EmailMessageRepository>();
            this.LookupEquiryOrigions = new ObservableListSource<LookupEquiryOrigion>();
            this.Notifications = new ObservableListSource<Notification>();
            this.EnquiryForCoursesNotRunByMCDs = new ObservableListSource<EnquiryForCoursesNotRunByMCD>();
            this.Individuals = new ObservableListSource<Individual>();
            this.Enrollments = new ObservableListSource<Enrollment>();
        }
    
        public int EnquiryID { get; set; }
        public System.DateTime EnquiryDate { get; set; }
        public int EnquiryStatusID { get; set; }
        public bool InitialConsultationComplete { get; set; }
        public bool InitialCurriculumEnquiryDocumentationSent { get; set; }
        public int CurriculumID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int EnrollmentQuanity { get; set; }
        public int ProgressFileID { get; set; }
    
        public virtual LookupEnquiryStatus LookupEnquiryStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<EquiryHistory> EquiryHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Company> Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<EmailMessageRepository> EmailMessageRepositories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<LookupEquiryOrigion> LookupEquiryOrigions { get; set; }
        public virtual Curriculum Curriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Notification> Notifications { get; set; }
        public virtual ProgressFile ProgressFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<EnquiryForCoursesNotRunByMCD> EnquiryForCoursesNotRunByMCDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Individual> Individuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Enrollment> Enrollments { get; set; }
    }
}
