//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquiryHistory
    {
        public int EnqueryHistoryID { get; set; }
        public int EnquiryID { get; set; }
        public int EmployeeID { get; set; }
        public int LookupEquiyHistoryTypeID { get; set; }
        public System.DateTime DateEnquiryUpdated { get; set; }
        public string EnquiryNotes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Enquiry Enquiry { get; set; }
        public virtual LookupEquiryHistoryType LookupEquiryHistoryType { get; set; }
    }
}
