//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facilitator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facilitator()
        {
            this.FacilitatorAssociatedCourses = new ObservableListSource<FacilitatorAssociatedCourse>();
            this.FacilitatorQualifications = new ObservableListSource<FacilitatorQualification>();
            this.FacilitatorSetaAccreditations = new ObservableListSource<FacilitatorSetaAccreditation>();
            this.Schedules = new ObservableListSource<Schedule>();
        }
    
        public int FacilitatorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<FacilitatorAssociatedCourse> FacilitatorAssociatedCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<FacilitatorQualification> FacilitatorQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<FacilitatorSetaAccreditation> FacilitatorSetaAccreditations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Schedule> Schedules { get; set; }
        public virtual Individual Individual { get; set; }
    }
}
