//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Individual()
        {
            this.Companies = new ObservableListSource<Company>();
            this.Enquiries = new ObservableListSource<Enquiry>();
            this.ContactDetails = new ObservableListSource<ContactDetail>();
            this.Addresses = new ObservableListSource<Address>();
        }
    
        public int IndividualID { get; set; }
        public int TitleID { get; set; }
        public string IndividualFirstName { get; set; }
        public string IndividualSecondName { get; set; }
        public string IndividualLastname { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Assessor Assessor { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Facilitator Facilitator { get; set; }
        public virtual LookupTitle LookupTitle { get; set; }
        public virtual NextOfKin NextOfKin { get; set; }
        public virtual Student Student { get; set; }
        public virtual SystemAdministrator SystemAdministrator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Company> Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Enquiry> Enquiries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<ContactDetail> ContactDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Address> Addresses { get; set; }
    }
}
