//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupEmailMessageRepositoryHistoryTrancationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LookupEmailMessageRepositoryHistoryTrancationType()
        {
            this.EmailMessageRepositoryHistories = new ObservableListSource<EmailMessageRepositoryHistory>();
        }
    
        public int EmailMessageRepositoryHistoryTrancationTypeID { get; set; }
        public string EmailMessageRepositoryHistoryTrancationType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<EmailMessageRepositoryHistory> EmailMessageRepositoryHistories { get; set; }
    }
}
