//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupSectionalEnrollmentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LookupSectionalEnrollmentType()
        {
            this.ApprienticeshipEnrollments = new ObservableListSource<ApprienticeshipEnrollment>();
        }
    
        public int LookupSectionalEnrollmentTypeID { get; set; }
        public string LookupSectionalEnrollmentTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<ApprienticeshipEnrollment> ApprienticeshipEnrollments { get; set; }
    }
}
