//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessageTemplate()
        {
            this.Files = new ObservableListSource<File>();
        }
    
        public int MessageTemplateID { get; set; }
        public int ProcessStepID { get; set; }
        public string Message { get; set; }
        public System.DateTime DateLastUpdated { get; set; }
    
        public virtual LookupProcessStep LookupProcessStep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<File> Files { get; set; }
    }
}
