//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffSiteSchedule
    {
        public int ScheduleID { get; set; }
        public int AddressID { get; set; }
        public System.DateTime DateLastModified { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
