//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgressFile()
        {
            this.Enquiries = new ObservableListSource<Enquiry>();
            this.Enrollments = new ObservableListSource<Enrollment>();
        }
    
        public int ProgressFileID { get; set; }
        public int ProgressFileTypeID { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual CompanyProgressFile CompanyProgressFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Enquiry> Enquiries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Enrollment> Enrollments { get; set; }
        public virtual LookupProgessFileType LookupProgessFileType { get; set; }
        public virtual StudentProgressFile StudentProgressFile { get; set; }
    }
}
