//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicHoliday
    {
        public int PublicHolidayID { get; set; }
        public System.DateTime PublicHolidayDate { get; set; }
        public string PublicHolidayYear { get; set; }
    }
}
