//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemAdministrator
    {
        public int SystemAdministratorID { get; set; }
        public string SystemUserName { get; set; }
        public string SystemUserPassword { get; set; }
    
        public virtual Individual Individual { get; set; }
    }
}
